/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import Conexion.Conexion;
import controlador.ctrlAspirante;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import modelo.aspirante;
import modelo.documentacion;
import modelo.examen;
import modelo.ofertaAcademica;
import modelo.usuario;

/**
 *
 * @author 52951
 */
public class Aspirante extends javax.swing.JFrame {

    /**
     * Creates new form Aspirante
     */
    public Aspirante() {
        initComponents();
        rellenarcomboespecialidades("clave_especialidad");
        rellenarcombodiscapacidad("nombre_discapacidad");
        rellenarcomboexamenes("folio_examen");
        rellenarcombotipodeesculea();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_direccion = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txt_escuelaprocedencia = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        txt_cct = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txttelefonotutor = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtnombrecompletotutor = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_telefono = new javax.swing.JTextField();
        txt_curp = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_ape_pat = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_ape_mat = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btn_aceptar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        checkfotos = new javax.swing.JCheckBox();
        checkConstancia = new javax.swing.JCheckBox();
        checkcertificado = new javax.swing.JCheckBox();
        checkcertificadobuenaconducta = new javax.swing.JCheckBox();
        checkcomprobante = new javax.swing.JCheckBox();
        checkacta = new javax.swing.JCheckBox();
        btn_buscar = new javax.swing.JButton();
        btn_actualizar = new javax.swing.JButton();
        txt_correo1 = new javax.swing.JTextField();
        LIMPIAR = new javax.swing.JButton();
        checkcurp = new javax.swing.JCheckBox();
        combodiscapacidad = new javax.swing.JComboBox<>();
        comboexamen = new javax.swing.JComboBox<>();
        combotiposecundaria = new javax.swing.JComboBox<>();
        txt_matricula1 = new javax.swing.JTextField();
        comboespecialidad = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Aspirante");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel13.setText("Folio del examen:");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel15.setText("Escuela de procedencia:");

        txt_escuelaprocedencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_escuelaprocedenciaActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel16.setText("CCT:");

        txt_cct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cctActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel6.setText("Tipo de discapacidad:");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel17.setText("Tipo de secundaria:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel7.setText("Telefono:");

        jLabel18.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N
        jLabel18.setText("INGRESE LOS DATOS DEL TUTOR");
        jLabel18.setMaximumSize(new java.awt.Dimension(200, 25));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel19.setText("Nombre completo:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel8.setText("Correo electronico:");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel20.setText("Telefono:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel9.setText("CURP:");

        txt_telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_telefonoActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel10.setText("Especialidad solicitada:");

        jLabel1.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N
        jLabel1.setText("INGRESE LOS DATOS DEL ASPIRANTE");
        jLabel1.setMaximumSize(new java.awt.Dimension(200, 25));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel2.setText("Nombre(s):");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel3.setText("Primer apellido:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel4.setText("Segundo apellido");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel5.setText("Matricula del aspirante:");

        btn_aceptar.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn_aceptar.setText("AGREGAR");
        btn_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aceptarActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel11.setText("Dirección:");

        jLabel12.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N
        jLabel12.setText("DOCUMENTACIÓN");
        jLabel12.setMaximumSize(new java.awt.Dimension(200, 25));

        checkfotos.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        checkfotos.setText("Fotos");
        checkfotos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkfotosActionPerformed(evt);
            }
        });

        checkConstancia.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        checkConstancia.setText("Constancia de estudios de sencundaria");
        checkConstancia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkConstanciaActionPerformed(evt);
            }
        });

        checkcertificado.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        checkcertificado.setText("Certificado de estudios de sencundaria");
        checkcertificado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkcertificadoActionPerformed(evt);
            }
        });

        checkcertificadobuenaconducta.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        checkcertificadobuenaconducta.setText("Certificado de buena conducta");
        checkcertificadobuenaconducta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkcertificadobuenaconductaActionPerformed(evt);
            }
        });

        checkcomprobante.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        checkcomprobante.setText("Comprobante de domicilio");
        checkcomprobante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkcomprobanteActionPerformed(evt);
            }
        });

        checkacta.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        checkacta.setText("Acta de nacimiento");
        checkacta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkactaMouseClicked(evt);
            }
        });
        checkacta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkactaActionPerformed(evt);
            }
        });

        btn_buscar.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn_buscar.setText("BUSCAR");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        btn_actualizar.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn_actualizar.setText("ACTUALIZAR");
        btn_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizarActionPerformed(evt);
            }
        });

        txt_correo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_correo1ActionPerformed(evt);
            }
        });

        LIMPIAR.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        LIMPIAR.setText("LIMPIAR");
        LIMPIAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LIMPIARActionPerformed(evt);
            }
        });

        checkcurp.setText("CURP");

        txt_matricula1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_matricula1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(339, 339, 339)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(checkacta)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(checkcurp)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(checkfotos)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(checkcertificadobuenaconducta)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(checkConstancia)
                                        .addGap(18, 18, 18)
                                        .addComponent(checkcertificado)
                                        .addGap(18, 18, 18)
                                        .addComponent(checkcomprobante))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel7)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txt_telefono))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txt_ape_pat, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabel4)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txt_ape_mat, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jLabel9)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txt_curp, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel8)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txt_correo1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jLabel6)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(combodiscapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(comboespecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txt_direccion)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_escuelaprocedencia, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_cct, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(combotiposecundaria, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_matricula1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_actualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LIMPIAR))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(268, 268, 268)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(422, 422, 422)
                        .addComponent(btn_aceptar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(284, 284, 284)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboexamen, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(0, 0, 0)
                        .addComponent(txtnombrecompletotutor, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txttelefonotutor, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(btn_buscar)
                    .addComponent(btn_actualizar)
                    .addComponent(LIMPIAR)
                    .addComponent(txt_matricula1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txt_ape_pat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txt_ape_mat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txt_curp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel6)
                    .addComponent(txt_correo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combodiscapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(comboespecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_direccion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txt_escuelaprocedencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(txt_cct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(combotiposecundaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(comboexamen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txtnombrecompletotutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(txttelefonotutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkacta)
                    .addComponent(checkConstancia)
                    .addComponent(checkcertificado)
                    .addComponent(checkcomprobante))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkfotos)
                    .addComponent(checkcertificadobuenaconducta)
                    .addComponent(checkcurp))
                .addGap(18, 18, 18)
                .addComponent(btn_aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aceptarActionPerformed

        int respuesta = JOptionPane.showConfirmDialog(null, "¿Esta seguro de registra al aspirante?, revise bien los datos", "Confirmación", JOptionPane.YES_NO_OPTION);

        if (respuesta == JOptionPane.YES_OPTION) {

            validarNotNullsAgregar(txt_nombre.getText(), txt_ape_pat.getText(), txt_curp.getText(), txt_correo1.getText(), txt_telefono.getText(), txtnombrecompletotutor.getText(), txttelefonotutor.getText(), txt_direccion.getText()
                    + txt_cct.getText(), txt_escuelaprocedencia.getText());

        }
    }//GEN-LAST:event_btn_aceptarActionPerformed

    private void txt_telefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_telefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_telefonoActionPerformed

    private void txt_cctActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cctActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cctActionPerformed

    private void checkfotosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkfotosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkfotosActionPerformed

    private void checkConstanciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkConstanciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkConstanciaActionPerformed

    private void checkcertificadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkcertificadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkcertificadoActionPerformed

    private void checkcertificadobuenaconductaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkcertificadobuenaconductaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkcertificadobuenaconductaActionPerformed

    private void checkcomprobanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkcomprobanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkcomprobanteActionPerformed

    private void txt_escuelaprocedenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_escuelaprocedenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_escuelaprocedenciaActionPerformed

    private void checkactaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkactaMouseClicked

    }//GEN-LAST:event_checkactaMouseClicked

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        String matricula = "";
        matricula = txt_matricula1.getText();

        BuscarAspirante(matricula);


    }//GEN-LAST:event_btn_buscarActionPerformed

    private void btn_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizarActionPerformed

        int respuesta = JOptionPane.showConfirmDialog(null, "¿Esta seguro de actualizar el aspirante?", "Confirmación", JOptionPane.YES_NO_OPTION);

        if (respuesta == JOptionPane.YES_OPTION) {

            validarNotNullActualizar(txt_nombre.getText(), txt_ape_pat.getText(), txt_curp.getText(), txt_correo1.getText(), txt_telefono.getText(), txtnombrecompletotutor.getText(), txttelefonotutor.getText(), txt_direccion.getText()
                    + txt_cct.getText(), txt_escuelaprocedencia.getText());

           // TODO add your handling code here:      

        }

    }//GEN-LAST:event_btn_actualizarActionPerformed

    private void txt_correo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_correo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_correo1ActionPerformed

    private void checkactaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkactaActionPerformed

    }//GEN-LAST:event_checkactaActionPerformed

    private void LIMPIARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LIMPIARActionPerformed
        limpiar();
    }//GEN-LAST:event_LIMPIARActionPerformed

    private void txt_matricula1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_matricula1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_matricula1ActionPerformed

    //metodo para registrar el aspirante validando que no se repitan matriculas
    private void registrarAspirante() {

        aspirante asp = new aspirante();
        examen exa = new examen();
        documentacion doc = new documentacion();
        documentacion doc2 = new documentacion();
        ofertaAcademica oA = new ofertaAcademica();
        String matricula = null;

        ctrlAspirante ctrlaspirante = new ctrlAspirante();

        if (txt_matricula1.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Llene los campos");
        } else {
            if (!ctrlaspirante.existeAspirante(txt_matricula1.getText().trim())) {
                asp.setMatricula(txt_matricula1.getText().trim());
                asp.setNombre(txt_nombre.getText().trim());
                asp.setApe_pat(txt_ape_pat.getText().trim());
                asp.setApe_mat(txt_ape_mat.getText().trim());
                asp.setCurp(txt_curp.getText().trim());
                asp.setCorreo(txt_correo1.getText().trim());
                asp.setNum_telefono(txt_telefono.getText().trim());
                String discapacidad;
                discapacidad = combodiscapacidad.getSelectedItem().toString();
                asp.setTipo_discapacidad(discapacidad);
                asp.setNombre_tutor(txtnombrecompletotutor.getText().trim());
                asp.setTelefono_tutor(txttelefonotutor.getText());
                asp.setDireccion(txt_direccion.getText().trim());
                asp.setCCT(txt_cct.getText().trim());
                String tiposecu;
                tiposecu = combotiposecundaria.getSelectedItem().toString();
                asp.setTipo_secundaria(tiposecu);
                asp.setNombre_secundaria(txt_escuelaprocedencia.getText().trim());
                asp.setNombre_secundaria(txt_escuelaprocedencia.getText().trim());
                String especialidad;
                especialidad = comboespecialidad.getSelectedItem().toString();
                System.out.println(especialidad);
                asp.setClave_especialidad(especialidad);
                String folioexamen;
                folioexamen = comboexamen.getSelectedItem().toString();
                asp.setFolio_examen(folioexamen);

                //doccumentacion
                int entregado = 0;

                doc.setMatricula(txt_matricula1.getText());
                if (checkacta.isSelected()) {
                    entregado = 1;
                    doc.setActa(entregado);
                } else {
                    entregado = 0;
                    doc.setActa(entregado);
                }
                if (checkConstancia.isSelected()) {
                    entregado = 1;
                    doc.setConstancia_secu(entregado);
                } else {
                    entregado = 0;
                    doc.setConstancia_secu(entregado);
                }
                if (checkcertificado.isSelected()) {
                    entregado = 1;
                    doc.setCertificado_secu(entregado);
                } else {
                    entregado = 0;
                    doc.setCertificado_secu(entregado);
                }
                if (checkcomprobante.isSelected()) {
                    entregado = 1;
                    doc.setComprobante_domicilio(entregado);
                } else {
                    entregado = 0;
                    doc.setComprobante_domicilio(entregado);;
                }
                if (checkcurp.isSelected()) {

                    entregado = 1;
                    doc.setCurp(entregado);
                } else {
                    entregado = 0;
                    doc.setCurp(entregado);
                }
                if (checkfotos.isSelected()) {
                    entregado = 1;
                    doc.setFotos(entregado);
                } else {
                    entregado = 0;
                    doc.setFotos(entregado);
                }
                if (checkcertificadobuenaconducta.isSelected()) {
                    entregado = 1;
                    doc.setCertificado_conducta(entregado);
                } else {
                    entregado = 0;
                    doc.setCertificado_conducta(entregado);
                }

                if (ctrlaspirante.Guadar(asp, exa, doc, matricula, doc2)) {
                    JOptionPane.showMessageDialog(null, "Aspirante guardado correctamente");

                } else {
                    JOptionPane.showMessageDialog(null, "Error al guardar aspirante");
                }
            } else {
                JOptionPane.showMessageDialog(null, "El aspirante ya existe");
                limpiar();
            }

        }

    }

    //metodo para actualizar estudiante ingresando la matricula
    private void ActualizarAspirante() {
        aspirante asp = new aspirante();
        examen exa = new examen();
        documentacion doc = new documentacion();

        ctrlAspirante ctrlaspirante = new ctrlAspirante();

        if (txt_matricula1.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Llene los campos");
        } else {
            if (ctrlaspirante.existeAspirante(txt_matricula1.getText().trim())) {
                asp.setMatricula(txt_matricula1.getText().trim());
                asp.setNombre(txt_nombre.getText().trim());
                asp.setApe_pat(txt_ape_pat.getText().trim());
                asp.setApe_mat(txt_ape_mat.getText().trim());
                asp.setCurp(txt_curp.getText().trim());
                asp.setCorreo(txt_correo1.getText().trim());
                asp.setNum_telefono(txt_telefono.getText().trim());
                String discapacidad;
                discapacidad = combodiscapacidad.getSelectedItem().toString();
                asp.setTipo_discapacidad(discapacidad);
                String tiposecu;
                tiposecu = combotiposecundaria.getSelectedItem().toString();
                asp.setTipo_secundaria(tiposecu);
                asp.setDireccion(txt_direccion.getText().trim());
                asp.setCCT(txt_cct.getText().trim());
                String especialidad;
                especialidad = comboespecialidad.getSelectedItem().toString();

                asp.setNombre_secundaria(txt_escuelaprocedencia.getText().trim());
                asp.setNombre_tutor(txtnombrecompletotutor.getText().trim());
                asp.setTelefono_tutor(txttelefonotutor.getText());

                //doccumentacion
                int entregado = 0;

                doc.setMatricula(txt_matricula1.getText());

                if (checkacta.isSelected()) {
                    entregado = 1;
                    doc.setActa(entregado);
                } else {
                    entregado = 0;
                    doc.setActa(entregado);
                }
                if (checkConstancia.isSelected()) {
                    entregado = 1;
                    doc.setConstancia_secu(entregado);
                } else {
                    entregado = 0;
                    doc.setConstancia_secu(entregado);
                }
                if (checkcertificado.isSelected()) {
                    entregado = 1;
                    doc.setCertificado_secu(entregado);
                } else {
                    entregado = 0;
                    doc.setCertificado_secu(entregado);
                }
                if (checkcomprobante.isSelected()) {
                    entregado = 1;
                    doc.setComprobante_domicilio(entregado);
                } else {
                    entregado = 0;
                    doc.setComprobante_domicilio(entregado);
                }
                if (checkcurp.isSelected()) {
                    entregado = 1;
                    doc.setCurp(entregado);
                } else {
                    entregado = 0;
                    doc.setCurp(entregado);
                }
                if (checkfotos.isSelected()) {
                    entregado = 1;
                    doc.setFotos(entregado);
                } else {
                    entregado = 0;
                    doc.setFotos(entregado);
                }
                if (checkcertificadobuenaconducta.isSelected()) {
                    entregado = 1;
                    doc.setCertificado_conducta(entregado);
                } else {
                    entregado = 0;
                    doc.setCertificado_conducta(entregado);
                }

                String cadena = txt_matricula1.getText();

                if (ctrlaspirante.Actualizar(asp, exa, doc)) {
                    JOptionPane.showMessageDialog(null, "Aspirante actualizado correctamente");
                } else {
                    JOptionPane.showMessageDialog(null, "REVISE QUE TODOS LOS DATOS SEAN CORRECTOS");
                }
            } else {
                JOptionPane.showMessageDialog(null, "El aspirante ya existe");

            }

        }

    }

    //metodo para buscar aspirante ingresando la matricula
    private void BuscarAspirante(String matricula) {
        try {
            Connection con = Conexion.conectar();
            PreparedStatement pst = con.prepareStatement("SELECT * FROM aspirante INNER JOIN documentacion_por_aspirante ON aspirante.matricula = documentacion_por_aspirante.matricula"
                    + " WHERE aspirante.matricula = '" + matricula + "'");
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {

                txt_matricula1.setText(rs.getString("matricula"));
                txt_nombre.setText(rs.getString("nombre"));
                txt_ape_pat.setText(rs.getString("ape_pat"));
                txt_ape_mat.setText(rs.getString("ape_mat"));
                txt_curp.setText(rs.getString("curp"));
                txt_correo1.setText(rs.getString("correo"));
                txt_telefono.setText(rs.getString("num_telefono"));
                txt_correo1.setText(rs.getString("correo"));

                txt_direccion.setText(rs.getString("direccion"));
                txt_escuelaprocedencia.setText(rs.getString("nombre_secundaria"));
                txt_cct.setText(rs.getString("CCT"));

                txtnombrecompletotutor.setText(rs.getString("nombre_tutor"));
                txttelefonotutor.setText(rs.getString("telefono_tutor"));

                checkacta.setSelected(rs.getBoolean("acta_nacimiento"));
                checkConstancia.setSelected(rs.getBoolean("constancia_secundaria"));
                checkcertificado.setSelected(rs.getBoolean("certificado_secu"));
                checkcomprobante.setSelected(rs.getBoolean("comprobante_domicilio"));
                checkcurp.setSelected(rs.getBoolean("curpdoc"));
                checkfotos.setSelected(rs.getBoolean("fotos"));
                checkcertificadobuenaconducta.setSelected(rs.getBoolean("certificado_conducta"));

                // boolean clave = rs.getBoolean("entregado");
                //JOptionPane.showMessageDialog(null, clave);
            } else {
                JOptionPane.showMessageDialog(null, "ingrese una matricula existente");
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);

        }

    }

    //rellenar combo de especialidades disponibles
    public void rellenarcomboespecialidades(String matricula) {

        String sql = "select * from plan_estudios";
        Statement st;

        try {
            Connection cn = Conexion.conectar();
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {
                comboespecialidad.addItem(rs.getString(matricula));

            }

        } catch (SQLException e) {
            System.out.println("Error al consultar" + e);
        }
    }

    //rellenar combo de examenes
    public void rellenarcomboexamenes(String folio) {

        String sql = "select * from examen";
        Statement st;

        try {
            Connection cn = Conexion.conectar();
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {
                comboexamen.addItem(rs.getString(folio));

            }

        } catch (SQLException e) {
            System.out.println("Error al consultar" + e);
        }
    }

    //rellenar combo de tipo de discapacidad 
    public void rellenarcombodiscapacidad(String discapacidad) {

        String sql = "select * from discapacidad";
        Statement st;

        try {
            Connection cn = Conexion.conectar();
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {
                combodiscapacidad.addItem(rs.getString(discapacidad));

            }

        } catch (SQLException e) {
            System.out.println("Error al consultar" + e);
        }
    }

    //rellenar el combo de tipo de escuela
    public void rellenarcombotipodeesculea() {

        combotiposecundaria.addItem("publica");
        combotiposecundaria.addItem("privada");

    }

    //metodo para limpiar
    public void limpiar() {
        txt_ape_mat.setText("");
        txt_ape_pat.setText("");
        txt_cct.setText("");
        txt_correo1.setText("");
        txt_curp.setText("");
        txt_direccion.setText("");
        txt_escuelaprocedencia.setText("");
        txt_matricula1.setText("");
        txt_nombre.setText("");
        txt_telefono.setText("");
        txtnombrecompletotutor.setText("");
        txttelefonotutor.setText("");
        checkConstancia.setSelected(false);
        checkacta.setSelected(false);
        checkcertificado.setSelected(false);
        checkcertificadobuenaconducta.setSelected(false);
        checkcomprobante.setSelected(false);
        checkcurp.setSelected(false);
        checkfotos.setSelected(false);

    }

    //Metodo para validar el formulario
    public boolean validarNombre(String nombre) {
        return nombre != null && !nombre.isEmpty();
    }

    public boolean validarApellidoPaterno(String apePat) {
        return apePat != null && !apePat.isEmpty();
    }

    public boolean validarCurp(String curp) {
        return curp != null && !curp.isEmpty();
    }

    public boolean validarCorreo(String correo) {
        return correo != null && !correo.isEmpty();
    }

    public boolean validarNumerodeTelefono(String telefono) {
        return telefono != null && !telefono.isEmpty();
    }

    public boolean validarNombreTutor(String nombreTutor) {
        return nombreTutor != null && !nombreTutor.isEmpty();
    }

    public boolean validarDireccion(String direccion) {
        return direccion != null && !direccion.isEmpty();
    }

    public boolean validarCCT(String cct) {
        return cct != null && !cct.isEmpty();
    }

    public boolean validarNombreSecundaria(String nombreSecundaria) {
        return nombreSecundaria != null && !nombreSecundaria.isEmpty();
    }

    public void validarNotNullsAgregar(String nombre, String apePat, String curp, String correo, String telefono, String nombreTutor, String direccion, String cct, String nombreSecundaria) {

        if (validarNombre(nombre) && validarApellidoPaterno(apePat) && validarCurp(curp) && validarCorreo(correo)
                && validarNumerodeTelefono(telefono) && validarNombreTutor(nombreTutor) && validarDireccion(direccion) && validarDireccion(direccion) && validarCCT(cct) && validarNombreSecundaria(nombreSecundaria)) {
            registrarAspirante();
            limpiar();
        } else {

            JOptionPane.showMessageDialog(null, "Ingrese todos los datos obligatorios, por favor");
        }

    }

    public void validarNotNullActualizar(String nombre, String apePat, String curp, String correo, String telefono, String nombreTutor, String direccion, String cct, String nombreSecundaria) {

        if (validarNombre(nombre) && validarApellidoPaterno(apePat) && validarCurp(curp) && validarCorreo(correo)
                && validarNumerodeTelefono(telefono) && validarNombreTutor(nombreTutor) && validarDireccion(direccion) && validarDireccion(direccion) && validarCCT(cct) && validarNombreSecundaria(nombreSecundaria)) {
            ActualizarAspirante();

        } else {

            JOptionPane.showMessageDialog(null, "Ingrese todos los datos obligatorios, por favor");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LIMPIAR;
    private javax.swing.JButton btn_aceptar;
    private javax.swing.JButton btn_actualizar;
    private javax.swing.JButton btn_buscar;
    private javax.swing.JCheckBox checkConstancia;
    private javax.swing.JCheckBox checkacta;
    private javax.swing.JCheckBox checkcertificado;
    private javax.swing.JCheckBox checkcertificadobuenaconducta;
    private javax.swing.JCheckBox checkcomprobante;
    private javax.swing.JCheckBox checkcurp;
    private javax.swing.JCheckBox checkfotos;
    private javax.swing.JComboBox<String> combodiscapacidad;
    private javax.swing.JComboBox<String> comboespecialidad;
    private javax.swing.JComboBox<String> comboexamen;
    private javax.swing.JComboBox<String> combotiposecundaria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_ape_mat;
    private javax.swing.JTextField txt_ape_pat;
    private javax.swing.JTextField txt_cct;
    private javax.swing.JTextField txt_correo1;
    private javax.swing.JTextField txt_curp;
    private javax.swing.JTextField txt_direccion;
    private javax.swing.JTextField txt_escuelaprocedencia;
    private javax.swing.JTextField txt_matricula1;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_telefono;
    private javax.swing.JTextField txtnombrecompletotutor;
    private javax.swing.JTextField txttelefonotutor;
    // End of variables declaration//GEN-END:variables
}
