/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import java.awt.event.ActionEvent;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.KeyStroke;
import javax.swing.*;
import java.awt.event.ActionEvent;

/**
 *
 * @author 52951
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.setExtendedState(this.MAXIMIZED_BOTH);
        Hotkeys();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();
        jLabel2 = new javax.swing.JLabel();
        PanelMenu = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Aspirante = new javax.swing.JMenu();
        NuevoAspirante = new javax.swing.JMenuItem();
        NuevoAspirante1 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        ConsultaAspirante = new javax.swing.JMenuItem();
        ConsultaOfertaAcademica = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar2.add(jMenu1);

        jMenu3.setText("Edit");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("jMenu4");

        jMenuItem1.setText("jMenuItem1");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jRadioButtonMenuItem2.setSelected(true);
        jRadioButtonMenuItem2.setText("jRadioButtonMenuItem2");

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de administracion de fichas");
        setMaximumSize(new java.awt.Dimension(550, 550));
        setName("FrameMenu"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        PanelMenu.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 679, -1));

        jLabel4.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        PanelMenu.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 679, -1));

        getContentPane().add(PanelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 390));

        Aspirante.setText("Registro");

        NuevoAspirante.setText("Nuevo Aspirante");
        NuevoAspirante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevoAspiranteActionPerformed(evt);
            }
        });
        Aspirante.add(NuevoAspirante);

        NuevoAspirante1.setText("Registrar examen");
        NuevoAspirante1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevoAspirante1ActionPerformed(evt);
            }
        });
        Aspirante.add(NuevoAspirante1);

        jMenuBar1.add(Aspirante);

        jMenu5.setText("Consulta");

        ConsultaAspirante.setText("Consulta de aspirante");
        ConsultaAspirante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultaAspiranteActionPerformed(evt);
            }
        });
        jMenu5.add(ConsultaAspirante);

        ConsultaOfertaAcademica.setText("Consulta oferta academica");
        ConsultaOfertaAcademica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultaOfertaAcademicaActionPerformed(evt);
            }
        });
        jMenu5.add(ConsultaOfertaAcademica);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void NuevoAspiranteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoAspiranteActionPerformed
        Aspirante asp = new Aspirante();
        asp.setVisible(true);
    }//GEN-LAST:event_NuevoAspiranteActionPerformed

    private void ConsultaAspiranteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultaAspiranteActionPerformed
        ConsultaAspirante consulasp = new ConsultaAspirante();
        consulasp.setVisible(true);
    }//GEN-LAST:event_ConsultaAspiranteActionPerformed

    private void ConsultaOfertaAcademicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultaOfertaAcademicaActionPerformed
        ConsultaOfertaAcademica consuloferta = new ConsultaOfertaAcademica();
        consuloferta.setVisible(true);
    }//GEN-LAST:event_ConsultaOfertaAcademicaActionPerformed

    private void NuevoAspirante1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoAspirante1ActionPerformed
        CatalogoExamenes exa = new CatalogoExamenes();
        exa.setVisible(true);

    }//GEN-LAST:event_NuevoAspirante1ActionPerformed

    //hotkeys
    public void Hotkeys() {

        //Abrir La vista de registro de aspirante
        Action abrirResgistrodeAspirante = new AbstractAction("Aspirante") {
            @Override
            public void actionPerformed(ActionEvent e) {
                Aspirante asp = new Aspirante();
                asp.setVisible(true);

            }

        };

        KeyStroke keyStroke = KeyStroke.getKeyStroke("control S");
        InputMap inputMap = PanelMenu.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);
        ActionMap ActionMap = PanelMenu.getActionMap();
        inputMap.put(keyStroke, "Aspirante");
        ActionMap.put("Aspirante", abrirResgistrodeAspirante);

        //Abrir La vista de registro de examenes de admision
        Action abrirRegistrarExamen = new AbstractAction("Examen") {
            @Override
            public void actionPerformed(ActionEvent e) {
                Examen exa = new Examen();
                exa.setVisible(true);

            }

        };

        KeyStroke keyStroke2 = KeyStroke.getKeyStroke("control A");
        InputMap inputMap2 = PanelMenu.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);
        ActionMap ActionMap2 = PanelMenu.getActionMap();
        inputMap2.put(keyStroke2, "Examen");
        ActionMap2.put("Examen", abrirRegistrarExamen);

        //Abrir La vista de oferta academica
        Action abrirOfertaAcademica = new AbstractAction("OfertaAcademica") {
            @Override
            public void actionPerformed(ActionEvent e) {
                ConsultaOfertaAcademica consuloferta = new ConsultaOfertaAcademica();
                consuloferta.setVisible(true);

            }

        };

        KeyStroke keyStroke3 = KeyStroke.getKeyStroke("control D");
        InputMap inputMap3 = PanelMenu.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);
        ActionMap ActionMap3 = PanelMenu.getActionMap();
        inputMap3.put(keyStroke3, "OfertaAcademica");
        ActionMap3.put("OfertaAcademica", abrirOfertaAcademica);

    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);

            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Aspirante;
    private javax.swing.JMenuItem ConsultaAspirante;
    private javax.swing.JMenuItem ConsultaOfertaAcademica;
    private javax.swing.JMenuItem NuevoAspirante;
    private javax.swing.JMenuItem NuevoAspirante1;
    private javax.swing.JPanel PanelMenu;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    // End of variables declaration//GEN-END:variables
}
